name: Tests

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    
    steps:
      - uses: actions/checkout@v3
      - run: rustup update && rustup component add clippy rustfmt
      
      - name: Build
        run: cargo build
      
      - name: Test
        run: cargo test
      
      - name: Clippy
        run: cargo clippy
      
      - name: Format
        run: cargo fmt -- --check
