name: Tests

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Toolchain
        run: rustup update && rustup target add wasm32-unknown-unknown
      
      - name: Build
        run: cargo build
      
      - name: Test
        run: cargo test
      
      - name: Clippy
        run: cargo clippy
      
      - name: Format
        run: cargo fmt -- --check
